const data = {
  users: [
    {
      name: "shajjad shagor",
      email: "darkdream7400@gmail.com",
      password: "Aa123456@",
      phone: "1235698745",
      address: "Rangpur, Bangladesh",
      image: "default.png",
    },
    {
      name: "anabia",
      email: "anabia@gmail.com",
      password: "Aa123456@",
      phone: "3215698745",
      address: "Rangpur, Bangladesh",
      image: "default.png",
    },
    {
      name: "Silvi",
      email: "silvi@gmail.com",
      password: "Aa123456@",
      phone: "321568998745",
      address: "Rangpur, Bangladesh",
      image: "default.png",
    },
    {
      name: "sarmin",
      email: "sarmin@gmail.com",
      password: "Aa123456@",
      phone: "321556898745",
      address: "Rangpur, Bangladesh",
      image: "default.png",
    },
    {
      name: "pappu",
      email: "pappu@gmail.com",
      password: "Aa123456@",
      phone: "32156895445",
      address: "dhaka, Bangladesh",
      image: "default.png",
    },
    {
      name: "goffy",
      email: "goffy@gmail.com",
      password: "Aa123456@",
      phone: "321255628745",
      address: "Malay, Bangladesh",
      image: "default.png",
    },
  ],
  products: [
    {
      name: "Samsung Galaxy A13",
      slug: "samsung-galaxy-A13",
      description:
        "The Samsung Galaxy A13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).Liquid Retina HD display 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology 1792-by-828-pixel resolution at 326 ppi 1400:1 contrast ratio (typical) True Tone display Wide color display (P3) Haptic Touch 625 nits max brightness (typical) Fingerprint-resistant oleophobic coating Support for display of multiple languages and characters simultaneously",
      price: 699,
      image: "samgalaxyA13.jpg",
      sold: 20,
      quantity: 80,
      shipping: 0,
      category: "650280ef7148f9dbad07cba5",
    },
    {
      name: "iPhone 11",
      slug: "iphone-11",
      description:
        "The iPhone 11 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).Liquid Retina HD display 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology 1792-by-828-pixel resolution at 326 ppi 1400:1 contrast ratio (typical) True Tone display Wide color display (P3) Haptic Touch 625 nits max brightness (typical) Fingerprint-resistant oleophobic coating Support for display of multiple languages and characters simultaneously",
      price: 799,
      image: "iphone11.jpg",
      sold: 20,
      quantity: 80,
      shipping: 0,
      category: "650280d87148f9dbad07cba3",
    },
    {
      name: "iPhone 13",
      slug: "iphone-13",
      description:
        "The iPhone 11 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).Liquid Retina HD display 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology 1792-by-828-pixel resolution at 326 ppi 1400:1 contrast ratio (typical) True Tone display Wide color display (P3) Haptic Touch 625 nits max brightness (typical) Fingerprint-resistant oleophobic coating Support for display of multiple languages and characters simultaneously",
      price: 1499,
      image: "iphone13.jpg",
      sold: 15,
      quantity: 8,
      shipping: 5,
      category: "650280d87148f9dbad07cba3",
    },
    {
      name: "Samsung Galaxy S22",
      slug: "samsung-galaxy-S22",
      description:
        "The Samsung Galaxy S22 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).Liquid Retina HD display 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology 1792-by-828-pixel resolution at 326 ppi 1400:1 contrast ratio (typical) True Tone display Wide color display (P3) Haptic Touch 625 nits max brightness (typical) Fingerprint-resistant oleophobic coating Support for display of multiple languages and characters simultaneously",
      price: 1199,
      image: "samgalaxyS22.jpg",
      sold: 20,
      quantity: 80,
      shipping: 0,
      category: "650280ef7148f9dbad07cba5",
    },
    {
      name: "Samsung Galaxy S23",
      slug: "samsung-galaxy-S23",
      description:
        "The Samsung Galaxy S23 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).Liquid Retina HD display 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology 1792-by-828-pixel resolution at 326 ppi 1400:1 contrast ratio (typical) True Tone display Wide color display (P3) Haptic Touch 625 nits max brightness (typical) Fingerprint-resistant oleophobic coating Support for display of multiple languages and characters simultaneously",
      price: 1699,
      image: "samgalaxyS23.jpg",
      sold: 30,
      quantity: 70,
      shipping: 0,
      category: "650280ef7148f9dbad07cba5",
    },
  ],
};

module.exports = data;
